name: directory-listing
on: [push]

jobs:
  pages-directory-listing:
    runs-on: ubuntu-latest
    name: Directory Listings Index
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: definitions

      - name: Upload artifact
        id: deployment             # VERPLICHT: Geeft een ID aan dit artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: .                 # GEWELDIG BELANGRIJK: Een punt (.) uploadt de hele structuur

  deploy:
    needs: pages-directory-listing
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.0
